---
title: "Food Bank Demand"
author: "Noelle"
date: "2025-09-28"
output:
  pdf_document: default
  html_document: default
---
### Visualizing food bank demand in June 2024 using R
\
\
1. Import libraries
```{r import libraries, message=FALSE}
library(dplyr)
library(readr)
library(ggplot2)
library(lubridate)
```
\
\
2. Read file into tibble
```{r read file, message=FALSE}
visits <- read_csv('/Users/noellepastor/Library/CloudStorage/OneDrive-UTArlington/2025-2026 Career/SKILLS/Demand Forecasting for Dallas Food Bank/Synthetic_Food_Bank_Visits.csv')
```

```{r glimpse file, message=FALSE}
glimpse(visits)
```
\
\
3. Get visits from June of 2024. Summarize by number of **visits per day**.
```{r filter visits, message=FALSE}
by_day <- visits %>% 
  filter(year(Visit_Date)==2024, month(Visit_Date)==6) %>% 
  group_by(Visit_Date) %>% 
  summarize(num_visits = n())
```
\
\
4. Plot **Visit_Date** and **num_visits** in column chart.
```{r create chart, message=FALSE}
ggplot(by_day) +
  
  geom_col(aes(x=Visit_Date, y=num_visits, fill=num_visits)) +
  
  labs(
  x="Visit Date", y="Number of Visits",
  title = "Number of Visits in June",
  subtitle = "Noelle Pastor",
  caption = "Increased demand at end of each week and month.",
  fill="Visits") +
  
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5),
        plot.caption = element_text(hjust=0.5)
        ) 
``` 


# Alternate Column Chart Style
Highlight days with more than 140 visits to see trends.
\
```{r create chart 2, message=FALSE}

ggplot(by_day) +
  
  geom_col(aes(x=Visit_Date, y=num_visits),
          fill = ifelse(by_day$num_visits>125, "darkorange", "blue")) +
  
  labs(
  x="Visit Date", y="Number of Visits",
  title = "Number of Visits in June",
  subtitle = "Noelle Pastor",
  caption = "Increased demand at end of each week and month.",
  fill="Visits") +
  
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5),
        plot.caption = element_text(hjust=0.5)
        ) 
```

